### ISSUE TITLE
Data.Dll.dll can't be found.

### ISSUE THREAD

**Issue by TheKaijuGojira** [sonicretro/sa2-mod-loader#16]
Hello, I have been trying to troubleshoot an issue recently with the SA2 Mod Loader dealing with the loader not being able to find the Data.Dll.dll file. 

My process in extracting the files is that I extract them into the SA2 folder in the Steam Common program files, then move the resource file into the Mod Loader folder. 

After that, I get an error saying the specific file can't be found (Most likely the dll). What would you suggest on doing?

P.S: I am correctly putting the mods in the Mods folder. Should I move the Mod Manager into the main SA2 folder?

**Comment by MainMemory** [comment]
Extract the 7z directly into the main SA2 folder.

**Comment by Woolton** [comment]
> Extract the 7z directly into the main SA2 folder.

the 'main' folder being? resource?

**Comment by MainMemory** [comment]
The `Sonic Adventure 2` folder, with `sonic2app.exe` in it.

**Comment by SonicVegeta** [comment]
I tried that and it didn't work
